### ISSUE TITLE
Nem megy a ccs kód feltöltése.

### ISSUE THREAD

**Issue by McMarcyYT** [vngplanet/MineMarket#101]
Sziasztok van egy css kódom minemarkethez és azt szeretném megkérdezni hogy kell azt feltölteni mert hiába megyek oda ahol fel kell tölteni nem működik, valaki leírja hogy kéne?

**Comment by andris155** [comment]
A head html részbe linkeld be a css fájlt a saját oldaladról.
<link rel="stylesheet" type="text/css" href="oldalad/valami.css" />
