### ISSUE TITLE
Nem működik a minemarket!

### ISSUE THREAD

**Issue by SlideeeR** [vngplanet/MineMarket#105]
Valamelyik nap, megpróbáltam a clans.hu-n lévő minemarket plugint betölteni a szerverbe, az a menet hogy töltsem bele a plugin fájlba a Minemarket plugint és indítsam újra a szervert, én ezt megtettem és mikor beléptem a szerverre az általam készített map (pálya) eltűnt nem lehetett oda teleportálni. Kérnék egy kis segítséget- e szemppontból.

**Comment by andris155** [comment]
A MineMarket plugin nem töröl pályákat. Szinte biztosan más okozta a problémát.

**Comment by PlayS24** [comment]
Halihó! Megjavítottam a MineMarket pluginját, hogy működjön a legújabb szerver/java verziókon! Remélem segíteni tudtam ezzel pár embernek. Letöltési link: https://www.spigotmc.org/resources/minemarket-plugin-fixed-version-1-7x-1-16x.84842/
