### ISSUE TITLE
MineMarket reload

### ISSUE THREAD

**Issue by AimBloow** [vngplanet/MineMarket#106]
Sziasztok. Amint berakom a plugint automatikusan elkezd kb 2-3 percenként reloadolni. Gondoltam arra is hátha valami plugin végett, és nem. ameddig a secretkey nincs megadva semmi gond, amint beállitom egyből 2-3 percenként reload. Segitséget előre is köszönöm.

**Comment by andris155** [comment]
Milyen reload?

**Comment by AimBloow** [comment]
hát szervert újratölti , kárt nemokoz , csak ez ilyen állapotban használhatatlan.

**Comment by andris155** [comment]
Az lesz a probléma, hogy kiküldtél neki egy reload parancsot szerintem az admin felületről.

**Comment by andris155** [comment]
Generálj új kulcsot és ne küldj ki ilyen parancsokat. A régit pedig töröld.

**Comment by andris155** [comment]
Vagy lehet valamelyik termékhez írtál reload parancsot (?)

**Comment by AimBloow** [comment]
egy termékhez se írtam reload parancsot

**Comment by andris155** [comment]
Szerintem a legegyszerűbb ha generálsz egy új kulcsot, amire pedig beírtad a reloadot azt törlöd.

**Comment by AimBloow** [comment]
Rendben, köszi a kurvagyors segitséget :D
