### ISSUE TITLE
PayPal e-mail cím a HTML kódban

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#107]
A PayPal e-mail cím nincsen titkosítva a html kódban, ahogy ezt a modern oldalakon szokás. Ennek az az eredménye, hogy egy csomó spam e-mail jön arra az e-mail címre mindennap.
Jó lenne ha titkosítva lenne az e-mail cím a kódban, vagy benne se lenne.

**Comment by vngplanet** [comment]
Szia, a spam szűrést meg kell oldanod valahogy, jelenleg nincs más megoldás a paypal fizetés használatára.
