### ISSUE TITLE
Linuxon nem működik a MineMarket-PE plugin.

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#11]
Linuxon nem működik, és nem tudjuk mit kell telepíteni, vagy engedélyezni hozzá. (Windowson működik)
`29.05 00:00:12 [Server] Server thread/CRITICAL Could not execute task MineMarket\ScheduleTask: Call to undefined function MineMarket\simplexml_load_file()`

**Comment by andris155** [comment]
megoldva

**Comment by Fr3llyOfficial** [comment]
Esetleg publikus a megoldása?
2018-02-10 [20:11:19] [Server thread/CRITICAL]: Could not execute task MineMarket\ScheduleTask: Call to undefined function MineMarket\simplexml_load_file()
2018-02-10 [20:11:19] [Server thread/CRITICAL]: Error: "Call to undefined function MineMarket\simplexml_load_file()" (EXCEPTION) in "/MineMarket_v0.1.0.phar/src/MineMarket/timer" at line 22

**Comment by andris155** [comment]
Telepítsd a simplexml modult a php fájljaidba.

**Comment by Fr3llyOfficial** [comment]
A simplexml-t hol találom?

**Comment by andris155** [comment]
Legalább 3 napot rá szántam és nem találtam megoldást rá. A Genisys-es php fájlokban (7.0.xx) benne van. Azonban az újabb 7.2.x-es fájlokba nem találtam olyat amiben benne lenne és a mostani szerverfájlok meg már azt használják. Nem találtam meg azt sem, hogy kellene ezt beletelepíteni.

**Comment by Fr3llyOfficial** [comment]
Értem. Hát lesz dolgom utána nézni ennek az egésznek, hogy hogy is működik, de ezzel előrébb is jutottam, szóval köszönöm a segítséged.
