### ISSUE TITLE
Plugin hiba! SURGOS

### ISSUE THREAD

**Issue by Asdfos** [vngplanet/MineMarket#111]
Beteszem a plugint, ujraíndítottam a szerót bemásolom helyesen a kódot, ujra elindítom a szerót, es amikor rámegyek h parancs küldése vagy ha rangot akarnak vásárolni nem futassa le a parancsot. mindent próbáltam már de semmi. a Freemcservre.net ről van a szerverem, de ha csinálok egy házi szervert ott müködik. Könyörgöm segítsen valaki

**Comment by PlayS24** [comment]
Halihó! Megjavítottam a MineMarket pluginját, hogy működjön a legújabb szerver/java verziókon! Remélem segíteni tudtam ezzel pár embernek. Letöltési link: [törölve]

**Comment by Asdfos** [comment]
Köszönöm szépen ☺️

PlayS24 <notifications@github.com> ezt írta (időpont: 2020. okt. 16., P
2:39):

**Comment by vngplanet** [comment]
@Asdfos  semmiképpen se használd a forkolt plugint, mert nem fog működni. Várd meg a hivatalos frissítést, ami napokon belül elérhető lesz.
