### ISSUE TITLE
Hibás adat FONTOS LENNE <PRÓ CSOMAG>

### ISSUE THREAD

**Issue by Suni2004** [vngplanet/MineMarket#114]
A mai nap véletlen kiléptem a MineMarket Adminból
Újra be szerettem volna lépni de azt írta ki hogy  "Hiba! Hibás adatok."
Kértem jelszóemlékeztetőt, nem kaptam meg az emailra
Miért van ez és hogyan tudom vissza szerezni az accountomat?

**Comment by vngplanet** [comment]
Szia, már működik az elfelejtett jelszó pótlás,, próbáld kérlek újra!
