### ISSUE TITLE
Nem kapom meg a pénzt ha valaki sms-el fizet.

### ISSUE THREAD

**Issue by TheKr1szTEN** [vngplanet/MineMarket#117]
Fizettek smssel és a játékos kapott egy kupon kódot, ami nem létezik. A pénz nekünk sem jött be, viszont az egyenleget levonta a szolgáltató.
2x történt meg 1016-os rendelések
![Screenshot_20200625-162828_Messages](https://user-images.githubusercontent.com/66673363/85858325-b9ab4c80-b7bb-11ea-93ed-850bf448fdb2.jpg)
![Screenshot_20200626-142310](https://user-images.githubusercontent.com/66673363/85858328-ba43e300-b7bb-11ea-97f1-1ca796b079de.jpg)

kel.

**Comment by TTRCharlie** [comment]
Ez az én szerveremen is előfordult, sőt nem is tudta a vásárló beaktiválni azt a kódot amit kapott.
