### ISSUE TITLE
Oldal/Fiók/SEO törlés

### ISSUE THREAD

**Issue by robizoli** [vngplanet/MineMarket#119]
Tisztelt Minemarket!

Szeretném, hogy töröljék az ehhez a fiókhoz kapcsolható Minemarket fiókot, azok webáruházát töröljék a Google és egyéb keresőmotorok keresési találatai között.

Az oldal a https://robizoliserver.minemarket.hu/ doaminen fut.

Üdvözlettel: robizoli / robizoli-kukac-robizoli-pont-hu

**Comment by andris155** [comment]
Szerintem ezt inkább e-mailben kellene nekik megírnod.

**Comment by vngplanet** [comment]
Törlésre így nincs lehetőség, Függesszed fel a boltodat adminfelületen.
