### ISSUE TITLE
EDSMS Feldolgozó Fájl

### ISSUE THREAD

**Issue by sarkanyka444** [vngplanet/MineMarket#123]
Üdv! Saját EDSMS rendszert szernék használni a minemarketemben. Ebben tudnának segíteni?

**Comment by andris155** [comment]
A MineMarket api-val megtudod csinálni, hogy jóváírja a kreditet a felhasználóknak. Viszont ezt is illetve minden mást is neked kell megoldani. A vgh.hu-nál a tulaj elég korrekt ott nekünk ezt ő csinálta meg. Ajánlom azt a hosting-ot.
