### ISSUE TITLE
Elérhetetlenné vált a fő minemarket.hu domain

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#124]
A http://minemarket.hu/ a phpmyadmin oldalára visz a minemarket oldala helyett.
A http://minemarket.hu/admin oldalt nem lehet elérni. 404 hibát ír.
A plugin nem tudja elérni a rendeléseket így a játékszerver és minemarket közötti kapcsolat nem működik.  java.util.concurrent.ExecutionException: java.io.FileNotFoundException: https://minemarket.hu/get_purchase.php?do=idkód

**Comment by vngplanet** [comment]
Ismét elérhető. A weboldal www-vel, és már ssl is megy szépen.

**Comment by andris155** [comment]
Az SSL rajta van és működik is, de azt nem mondanám, hogy szépen megy.
<img width="566" alt="Capture" src="https://user-images.githubusercontent.com/8324198/94272044-ccf8c000-ff42-11ea-8e55-11eb0d0a6000.PNG">

**Comment by vngplanet** [comment]
https://www.minemarket.hu
De, www-vel. Átirányítása még nem jó a sima urlről, max be cache-elte neked.

**Comment by andris155** [comment]
A www-s oldalon nem lehet belépni, de ott tényleg jó a https.

**Comment by andris155** [comment]
De ez már egy új hiba. Az oldal már elérhető.
