### ISSUE TITLE
Belépés gomb hiba mobiltelefonon

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#125]
Mobiltelefonon állított nézetben nem fér ki a belépés gomb így nem is működik.
![Screenshot_20200926-011947](https://user-images.githubusercontent.com/8324198/94323543-8df45a00-ff96-11ea-9a4a-6552885bb62f.png)

**Comment by Hatoskahun** [comment]
Ezer éve így van :( Már kapásból úgy keresek googlen a minemarketre hogy "minemarket admin". Így tudom elérni, mivel nincs gomb

**Comment by vngplanet** [comment]
Itt volt az ideje javítani.
