### ISSUE TITLE
Bonyolult belépés a www-s oldalon

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#127]
A www-s oldalon való belépés után át dob a nem www-s belépés oldalra belépés nélkül. Ezután ismét át kell lépni a www-s oldalra és így már belépve tölt be az admin oldal.

**Comment by str0nixofficial** [comment]
> A www-s oldalon való belépés után át dob a nem www-s belépés oldalra belépés nélkül. Ezután ismét át kell lépni a www-s oldalra és így már belépve tölt be az admin oldal.

Egyátalán még foglalkoznak a MineMarketet érintő hibákkal? Már egy általam fél éve jelentett hibára sem kaptam semmilyen visszajelzést, illetve magának az oldalnak is lejárt az SSL tanusítványa.

**Comment by andris155** [comment]
A www-s oldalon van új működő tanúsítvány. Végülis a webadminba belehet lépni és működnek is a dolgok, bár már az ikonok sem jelennek meg, mert frissíteni kellene a linkjüket. De a MineMarket kezelőn kívül ezt más úgy se látja.
A MineMarket mint oldal hát alapból elég gagyi szerintem. Nincs benne a mobilos nézet sem, bár amikor készült még annyira nem is volt elterjedt olyan 2014 körül. Meg vannak nem működő dolgok is benne. Viszont a pro verzióval a css és html szerkesztés résszel a mobilos nézet megcsinálható hozzá, a nem működő dolgok pedig javíthatók vagy kiszedhetőek az oldalról így. Illetve az alap kinézet is fejleszthető vele. Szerintem jelenleg csak annak éri meg a MineMarket aki a clans szerveréhez kapott Pro verziót, vagy megmaradt neki a Pro verzió. Az alap verziót én pedig senkinek sem ajánlanám.

**Comment by str0nixofficial** [comment]
Nos én rendelkezek egy clans.hu-nál bérelt szerverrel, viszont amikor megadom a webadmin belépési adataimat a Pro csomag aktiválásakor, akkor azt írja, hogy hibás felhasználónév és jelszó. Már ezt a hibát is jeleztem itt , viszont arra sem méltattak válaszolni. A hiba jelenleg is fennáll. A legidegesítőbb probléma pedig az, hogy a webszerveren található XML fájl oldalaknak nincsen működő SSL tanusítványa, így a Minecraft: Bedrock Edition-höz php nyelvben megírt plugin nem működik, mivel a php simplexml_load_file függvénye nem tudja az OpenSSL-el encryptelni az XML feldolgozó fájlt tartalmazó oldalt, így a plugin crasheli a szervert.  Próbáltam már a clans.hu vezetőségén keresztül elkérni a szolgáltatást üzemeltető illetékes elérhetőségét, de válaszra sem méltattak, tehát én ebből arra következtetek, hogy miután a MineMarketet a VNG Planet kft. átvette az InfinityHostingtól azóta erre a szolgáltatásra nagy ívben tesznek. Véleményem szerint örök hiba, és nagy ziccert hagynak ki a jelenlegi tulajdonosok.

**Comment by andris155** [comment]
A MineMarketPE-t régen át kellett írni (nyílt forráskódú volt.), hogy működjön. Van szerintem az xml részhez is normális tanúsítvány, csak www-vel kell írni a linket.

**Comment by andris155** [comment]
Illetve a php fájlokba bele kellett rakni ezt az xml dolgot. Alapból nincs benne és csak úgy nem működik ha nincs benne.

**Comment by andris155** [comment]
![Screenshot_20201007-071847](https://user-images.githubusercontent.com/8324198/95290400-75752100-086d-11eb-8a66-65a174e69e73.png)
Valamennyire foglalkoznak vele. Gondolom ahogy idő engedi. Tudtommal a tulaj csinálja ezt is és nincs rá külön ember. A végén az InfinityHosting se foglalkozott egyébként a MineMarket-el.

**Comment by andris155** [comment]
Azt pedig, hogy nem működik a Pro csomag a clans szerverhez inkább szerintem e-mailben írd meg nekik, vagy valahogy vedd fel a kapcsolatot a tulajdonossal.

**Comment by str0nixofficial** [comment]
> Illetve a php fájlokba bele kellett rakni ezt az xml dolgot. Alapból nincs benne és úgy nem működik ha nincs benne.

Már próbáltam, hogy a timer.php-ban lévő XML fájl helyének a linkjét átírom www-re, de úgy meg a boltban megtörtént vásárlás után nem fut le a parancs, viszont ha esetleg egy idő után valamiért lefut, akkor azonnal crasheli a szervert. Szerintem a simplxml_load_file php függvény igényli az SSL tanusítványt

**Comment by str0nixofficial** [comment]
> Illetve a php fájlokba bele kellett rakni ezt az xml dolgot. Alapból nincs benne és úgy nem működik ha nincs benne.

Tehát akkor le kell töltenem az XML fájlt, majd a link helyett a fájl elérési útvonalát kell a simplexml_load_file függvénynek megadnom?

**Comment by andris155** [comment]
De a www-s linken van SSL tanúsítvány ami pedig működik. Szóval az úgy érdekes.

**Comment by str0nixofficial** [comment]
> De a www-s linken van SSL tanúsítvány ami pedig működik. Szóval az úgy érdekes.

Próbálkoztam a link átírásával és a változás csak annyi volt, hogy miután elindítottam a szervert nem crashelt a plugin és azzal együtt a szerver azonnal, viszont amint egy parancsot lefuttatok a boltból azonnal crashel ugyan azzal az errorral.

**Comment by andris155** [comment]
Az új Pocketmine verziókra szerintem lehet frissíteni kell az egészet. Mióta nincs igény a Bedrock Edition szerverekre Magyarországon én már nem követem a változásokat ezzel kapcsolatban.

**Comment by str0nixofficial** [comment]
Már magát a plugint frissítettem a jelenlegi PocketMine API verzióra, csak az XML fájlal van a probléma, de a délután folyamán egy kicsit átírtam a plugin timer.php fájlját, így most egyelőre működik a dolog.

**Comment by PlayS24** [comment]
Halihó! Megjavítottam a MineMarket pluginját, hogy működjön a legújabb szerver/java verziókon! Remélem segíteni tudtam ezzel pár embernek. Letöltési link: https://www.spigotmc.org/resources/minemarket-plugin-fixed-version-1-7x-1-16x.84842/

**Comment by vngplanet** [comment]
Javítva.
