### ISSUE TITLE
Eltűnt/hibás regisztrációk - használhatatlanná vált a MineMarket

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#130]
A regisztrált játékosoknál jelenleg 3 van az admin oldalon miközben legalább 5000 regisztráció biztosan volt.
A belépésnél azt írja, hogy adjam meg a játékosnevem. De hiába írok be bármit is, sajnos nem menti el.
<img width="1039" alt="Capture" src="https://user-images.githubusercontent.com/8324198/97499001-6f0a2e80-196d-11eb-981e-c7e99f19b33e.PNG">

Ha regisztrálni akarnék új fiókot, akkor pedig azt írja, hogy az e-mail cím már foglalt.

**Comment by Hatoskahun** [comment]
Nekem is ugyanezt írja, az összes eddigi vásárláshoz tartozó név eltűnt. Nem lehet regisztrálni. Több ezer felhasználó neve tűnt el az adatbázisból. Tehát így a rang lejárat se tud működni.

**Comment by andris155** [comment]
A Luckperms-ben lehet adni időre rangokat. Szerintem úgy sokkal jobb megoldani a rang lejáratot. Megtudod oldani azt is vele, hogy ha többször vesz valaki rangot akkor adja hozzá a plusz időt a rangjához.

**Comment by Hatoskahun** [comment]
Persze értem, csak aki így oldotta meg az elbukta ezt most :(

**Comment by vngplanet** [comment]
Próbáld újra most kérlek.

**Comment by Hatoskahun** [comment]
Köszönjük, most már láthatóak a felhasználóak újra. A belépés is működik.
