### ISSUE TITLE
Minemarket nem működik

### ISSUE THREAD

**Issue by MatuPlays** [vngplanet/MineMarket#131]
Igazából annyi lenne a kérdésem,hogy miért nem működött nekem a minemarket parancs futtatás?Aktiváltam a secret key-t,beraltam a plugint.Luckpermset használok,nem tudom hogy azt támogatja e a minemarket,lehet az a baj.

**Comment by andris155** [comment]
A Luckperms parancsokat nekem hibátlanul lefuttatja. Nem azzal lesz gond.

**Comment by MatuPlays** [comment]
rendben,köszönöm!

András Marczinkó <notifications@github.com> ezt írta (időpont: 2020. nov.
22., V, 15:43):
