### ISSUE TITLE
Emelt Díjas SMS

### ISSUE THREAD

**Issue by Staiger69** [vngplanet/MineMarket#132]
Üdv, nemlehet emelt díjas SMS-el vásárolni  a webáruházban! Messengeren nem érem el önöket! Tudnának valami információkat adni?

**Comment by vngplanet** [comment]
Szia de lehet, legfeljebb neked vagy valakinek nem működik, mert nincs engedélyezve az EDSMS küldés. Csak itt tartunk ügyfélszolgálatot, és itt tudunk információt adni.
