### ISSUE TITLE
MineMarket.hu és az ehhez tartozó aldomainek webshopjai se érhetőek el.

### ISSUE THREAD

**Issue by Hatoskahun** [vngplanet/MineMarket#135]
![Screenshot_66](https://user-images.githubusercontent.com/24590434/99906704-d7340200-2cd8-11eb-848c-bff721978344.png)

**Comment by andris155** [comment]
Nekem se érhetőek el sajnos az oldalak. :(
![Screenshot_20201122-153844](https://user-images.githubusercontent.com/8324198/99906738-fd59a200-2cd8-11eb-80fd-d7ebdbdfdcbf.png)

**Comment by andris155** [comment]
Már működik.
