### ISSUE TITLE
Minemarket PayPal kifizetés

### ISSUE THREAD

**Issue by MatuPlays** [vngplanet/MineMarket#137]
Nagyon sok féle információt hallok ezügyben,mostanra már teljesen összezavarodtam. Sokan azt állítják,hogy ezek után kell adózni,számlát kiállítani,de valaki azt mondja,hogy nem kell.
Szeretnék egy hivatalos,végleges választ kapni,hogy mégis mi az igazság.
Nem akarok emiatt bajba kerülni..

15 yrs
 @vngplanet 
Köszönöm.

**Comment by vngplanet** [comment]
Szia, hívd fel a navot, ők adnak neked hivatalos tájékoztatást.. Bárhol bármikor pénzt fogadsz el, adóznod kell utána. Van egy éves limit ha jól emlékszem 200eFT / év, ami bevétel után nem kell adót fizetned mint MAGÁNSZEMÉLY.  Ilyen bevételek lehetnek pl  jófogáson vagy hardveraprón is eladott dolgaid, stb...
