### ISSUE TITLE
Lejárt ssl tanusítvány

### ISSUE THREAD

**Issue by Hatoskahun** [vngplanet/MineMarket#140]
![Screenshot_139](https://user-images.githubusercontent.com/24590434/104812886-afa77480-5805-11eb-96d1-cc154126bca6.png)
![Screenshot_140](https://user-images.githubusercontent.com/24590434/104812889-b209ce80-5805-11eb-98c1-ce73c0026037.png)
![Screenshot_141](https://user-images.githubusercontent.com/24590434/104812891-b59d5580-5805-11eb-9e45-17aed0090c2e.png)
![Screenshot_142](https://user-images.githubusercontent.com/24590434/104812901-c2ba4480-5805-11eb-8a15-b4b3c49b63bc.png)

**Comment by andris155** [comment]
<img width="300" alt="Screenshot 2021-01-16 213031" src="https://user-images.githubusercontent.com/8324198/104822358-27939000-5842-11eb-8b74-c18e2d212e9a.png">
