### ISSUE TITLE
Összes felhasználó törlődött

### ISSUE THREAD

**Issue by Hatoskahun** [vngplanet/MineMarket#149]
Törlődött az összes felhasználó a minemarket rendszeréből. Egyik Minemarketre se tudnak bejelentkezni.

**Comment by andris155** [comment]
Nálunk is sajnos ez a probléma.

**Comment by vngplanet** [comment]
Nem törlődött semmi. Hamarosan ismét láthatjátok.

**Comment by vngplanet** [comment]
> Nálunk is sajnos ez a probléma.

Leellenőriznéd kérlek, hogy nálad is rendben van már minden? Köszönöm.

**Comment by Hatoskahun** [comment]
> > Nálunk is sajnos ez a probléma.
> 
> Leellenőriznéd kérlek, hogy nálad is rendben van már minden? Köszönöm.

Újra látjuk a usereket, köszönjük az intézkedést.

**Comment by andris155** [comment]
Újra látom én is az összes felhasználót.
