### ISSUE TITLE
Hiba

### ISSUE THREAD

**Issue by Raxoray** [vngplanet/MineMarket#151]
A délutáni hibajelentés óta nem történt semmi. "hamarosan láthatjátok"
Akárki jelentkezik be, új Minecraft Felhasználót kér tőle, nem enged beírni semmit.
Abban az esetben ha új fiókot készítenek kiválóan működik a rendszer.

**Comment by vngplanet** [comment]
Nem írtuk hogy 5 perc, sem azt hogy 1 nap. A hamarosan az hamarosan, Mihelyst helyreállítják a fejlesztők, helyre fog jönni.
