### ISSUE TITLE
SMS fizetési hiba!

### ISSUE THREAD

**Issue by superrqjmi** [vngplanet/MineMarket#154]
Tisztelt MineMarket!
Nem lehet létrehozni új SMS-t!
Megcsinálom a Prefixet kiválasztom az SMS-t és beállítom a szorzót de nem történik semmi!

**Comment by relaxmmc** [comment]
Szia ! ugyanaz a hiba nekem is , a clans.hu megmondta a hibajegyben ... itt lehet megbeszelni azt ami nem megy , a minemarketnek pedig nincs egy telefonszama sem , amit elegge nem tartok korrektnek , szoval megvettem a szolgaltatast es nem tudom hasznalni szoval nagyon gondolkodom azon hogy irok egy emailt hogy feljelentem oket abban a ze setben hogyha megveszem nem lehet hasznalni !!!.

**Comment by vngplanet** [comment]
Senki sem írja elő hogy legyen telefonszám egy ingyenes szolgáltatáshoz. Nem vettél meg semmit, ez továbbra is ingyenes. Sajnáljuk ha neked nem működik, ez esetben nem kell használni.
