### ISSUE TITLE
Nem lefutott rendelések törlése

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#19]
Jelenleg a boltunkba olyan több 1000 rendelés van ami nem futott le, de nem tudjuk törölni, pedig ezek 90%-a felesleges már. Azt nézi, hogy online-e a játékos, de már azóta reset is volt a szerveren szóval tényleg felesleges nálunk már, és ha nem lép fel a játékos meg ugye nem fut le pl.: /gamemode 0 neve

**Comment by vngplanet** [comment]
Törölve vannak a parancsok, javítva lett.
