### ISSUE TITLE
Nem működnek a kuponkódok. (új hiba)

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#22]

**Comment by andris155** [comment]
Reprodukálás: Létrehozok egy kuponkódot bármilyen értékbe, majd mikor be akarnám írni azt írja, hogy nem található a kuponkód.

**Comment by gdavid04** [comment]
Nekem se. Többször is megpróbáltam.

**Comment by andris155** [comment]
Már működnek.
