### ISSUE TITLE
Megerősítő e-mail a regisztrációnál

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#25]
Sokan kamu e-mail címet adtak meg a minemarketen jó lenne, ha regisztrációhoz megerősítő e-mailt kellene elfogadni.

**Comment by gdavid04** [comment]
Ez tényleg hasznos lenne. Meg esetleg egy megerősítő parancs is lehetne amivel a játékos igazolná, hogy ő regisztrált az adott névvel.
