### ISSUE TITLE
Oldal hibák, és https hiányosságok.

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#38]
![kepkivagas](https://user-images.githubusercontent.com/8324198/28580420-be8e3ea6-715f-11e7-8e2b-b8cd0674749c.PNG)

**Comment by andris155** [comment]
![kepkivagas](https://user-images.githubusercontent.com/8324198/28581179-e6fabb38-7161-11e7-8bdd-f46c22658751.PNG)

**Comment by vngplanet** [comment]
Köszi, javítjuk őket!

**Comment by vngplanet** [comment]
Kijavítottuk, köszi. A meta error pedig egy bug ahogy olvastam, az így marad, mellesleg ezek  a hibák sem befolyásolták az ssl-t, legfeljebb nem töltött be, de ettől még valid volt az oldal.


![](https://i.gyazo.com/72af892759afd0165b622c8323d87b69.png)
