### ISSUE TITLE
A korlátlan kredit küldési limit nem működik.

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#39]
Azt írja a kredit küldési limit beállításokban, hogy ha 0-ra állítom korlátlan lesz. Viszont, ha beállítom 0 lesz a limit nem pedig korlátlan.

**Comment by vngplanet** [comment]
Küldési limit beállítása: -1:korlátlan kredit küldés, 0:küldés tiltása, egyéb szám maximumként funkcionál javítottuk, a -1 mindig is a korlátlant szokta jelenteni. 0 lett a kikapcsolása a küldésnek, ha pedig számot írsz annyi lesz a limit. Tesztelve admin és user oldalon is.

**Comment by andris155** [comment]
köszönjük!
