### ISSUE TITLE
Üres a Minemarket SMS feldolgozó fájl linkje.

### ISSUE THREAD

**Issue by Kbarni2** [vngplanet/MineMarket#46]
A Minemarket SMS feldolgozó fájl: http://minemarket.hu/gw/vngplanet.php Itt: (https://minemarket.hu/admin/payment_methods.php?method=edsms&new)

**Comment by vngplanet** [comment]
Szia, nem is lesz külön használható már, mivel csak zárt rendszerben érhető majd el, általunk engedett szolgáltatókkal.
Egyébként igen, azért üres mert nincs mit megjelenítsen, nem kapott semmilyen kérést, ez normális :)
