### ISSUE TITLE
Nem megy a CSS kódolás.

### ISSUE THREAD

**Issue by Kbarni2** [vngplanet/MineMarket#50]
A MineMarketben az Egyedi CSS-nél nem működik a CSS kód. Ha beírom: .paypalbutton {
         background-color: red;
}
Akkor nem lesz piros.

**Comment by andris155** [comment]
Így se működik?
```
.paypalbutton {
background-color: red !important;
}
```

**Comment by Kbarni2** [comment]
Nem.

**Comment by vngplanet** [comment]
Ez nem hiba, az egyéni stylusok használata megfelelően működik, css tudás frissítéshez ajánlom ezt az oldalt: https://www.w3schools.com/css/
