### ISSUE TITLE
Minemarket Widget javítási segítség

### ISSUE THREAD

**Issue by Gergely9135** [vngplanet/MineMarket#51]
Hello. 
Azt szeretném kérdezni, hogy mikor lesz jó az a widget, amelyik a szerver státuszát mutatja. Magyarul: Van egy házi Minecraft Szerverem. A routeremben forewardoltam is az IP-t meg a portot, más játékosok is fel tudnak jönni, de viszont a widget azt észleli, hogy nem fut a szerver, pedig rendesen beírtam a widgetbe a szerver IP-jét illetve a portját.
Viszlát. Segítségüket előre is köszönöm.

**Comment by vngplanet** [comment]
Szia, a widget státusz megfelelően működik.  Fejlesztés során vétett hibák jelzésére illetve ötletek megosztását szolgálja ez az oldal. Sajnos ügyfélszolgálatot itt nem tartunk. Megjegyzés: Bérelj normális játékszervert ami mehfelelően müködik. Ha hozzáértő személyekre bízod a szerver hostot, nem lesznek ilyen jellegű priblémáid.

**Comment by Gergely9135** [comment]
De én nem szeretnék bérelni sajátot. Alapból jó a szerverem. nekem a chat support azt írta hogy írjak ide egy bejelentőt és még azt is hogy a hiba javítás alatt

**Comment by vngplanet** [comment]
Továbbra is:  "Szia, a widget státusz megfelelően működik. "
