### ISSUE TITLE
MineMarket-API hiba történt

### ISSUE THREAD

**Issue by Gergely9135** [vngplanet/MineMarket#52]
a http://minemarket.hu/api nem működik. ezt adja ki:

ERROR 401 - Unauthorized!

The following error occurred:

The URL requested requires authorisation.

Please contact the webmaster with any queries.
                                                                           Powered by ISPConfig
ez mikor lesz javítv ha szabad kérdeznem??
választ előre is köszönöm

**Comment by vngplanet** [comment]
Megfelelően működik, helyes kérés esetén.

**Comment by andris155** [comment]
Nekem tökéletesen működik az API.

**Comment by andris155** [comment]
Csak az a hiba van benne, amit már leírtam.
