### ISSUE TITLE
Plugin hiba!

### ISSUE THREAD

**Issue by Sauron12** [vngplanet/MineMarket#53]
Mcpe minemarket plugin hibas!
Parancsot lejatsza de a megadot rangok nem kapjuk meg!

**Comment by PlayS24** [comment]
Halihó! Megjavítottam a MineMarket pluginját, hogy működjön a legújabb szerver/java verziókon! Remélem segíteni tudtam ezzel pár embernek. Letöltési link: https://www.spigotmc.org/resources/minemarket-plugin-fixed-version-1-7x-1-16x.84842/

**Comment by vngplanet** [comment]
@PlayS24  a plugint frissítjük, a saját javításodra nem lesz szükség, és használni sem lehet majd, de köszönjük. Kérlek ne add tovább másnak, és szedd le spigotról.
