### ISSUE TITLE
SMS

### ISSUE THREAD

**Issue by Kbarni2** [vngplanet/MineMarket#54]
Jelenleg a MineMarket-ben bent "ragadnak" a pénzek, mivel nem lehet átkér sehova. Így nem lehet fejlesztésre fordítani az az összeget, amivel támogatják a szervert.

**Comment by vngplanet** [comment]
Nem ragad bent semmi, clans.hu webadmin egyenlegre átkérhető.

**Comment by Kbarni2** [comment]
S hol is lehet ezt végrehajtani?

**Comment by Kbarni2** [comment]
S ha nem a Clans.hu-nál van szerverem?

**Comment by vngplanet** [comment]
Webadmin hibajelentőben lehet jelenleg átkérni míg nem lesz automatikus. Csak clans.huhoz kérhető az egyenleg.

**Comment by Kbarni2** [comment]
Oké.Köszi az infot.☺
