### ISSUE TITLE
Spawner hiba.

### ISSUE THREAD

**Issue by kisdomo1** [vngplanet/MineMarket#67]
Hali. mai nap folyamán azaz (2018.11.02) vettem egy zombi spawnert.
Megcsináltam neki a kis helyet meg mindent és amikor arra került a sor, hogy megnézzem mit alkottam akkor nagy csoda történt. Amikor le raktam át változott disznó spawnerré. 
Kértem segítséget és mondták, hogy ide írjak mert kapok valami jutalmat is :D 

Válaszodat előre is köszönöm. :) 
Üdv! pAdAwAn123

**Comment by andris155** [comment]
Kérj meg egy staff tagot, hogy váltsa be neki arra, amilyet vettél.

**Comment by vngplanet** [comment]
Játékszervereken való problémákért az üzemeltetőket keresd...
