### ISSUE TITLE
Nem működik a PayPal támogatás a kosárnál

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#68]
A kosárnál nem működik a PayPal fizetés. Nem írja jóvá és nem fizetett rendelést ír.

**Comment by Hatoskahun** [comment]
+1 És nagyon idegesítő mert a MineMarket rendszere se ír sokszor rendelést, van hogy jóvá se lehet írni mivel más e-mail címmel veszik mint amivel regisztrál.

**Comment by andris155** [comment]
Ha már javítani nem lehet, akkor legalább ez a rész legyen kiszedve a kosár oldalból. Pár perc az egész és sokat javítana a MineMarket-en. Az a baj, hogy hiába írom ki, hogy a kosárnál nem jó sajnos sokan nem olvassák el.
![Annotation 2019-04-16 140132](https://user-images.githubusercontent.com/8324198/56207914-34bd9280-6050-11e9-96ee-db49e364aafe.png)
