### ISSUE TITLE
Belső szerverhiba kredit küldésnél

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#8]
Ha úgy küldünk valakinek kreditet, hogy közben online az is akinek küldjük, akkor belső szerverhibát ír.

**Comment by vngplanet** [comment]
Hol külditek a kreditet pontosan?

**Comment by andris155** [comment]
A profilnál, tehát nem az Admin oldalon.

**Comment by vngplanet** [comment]
Működik a kredit küldés is.
