### ISSUE TITLE
Hiányzó MineMarket logó

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#81]
Régen volt egy logója is a MineMarket-nek, ami így nézett ki.
![jegyzet 2018-12-16 150432](https://user-images.githubusercontent.com/8324198/50054610-0bddcd00-0144-11e9-925f-cebd1f713087.jpg)

**Comment by poma123** [comment]
elvitte a sok hibajavítás :(

**Comment by andris155** [comment]
Pedig szerintem így volt szép. :/

**Comment by vngplanet** [comment]
@andris155 nincs meg sajnos a logó, így kaptuk, hogy már nem volt meg. Nem tudtam hogy volt, és nem is foglalkoztunk azzal hogy esetleg hiányzik onnan valami. Ha esetleg meg tudjuk valahonnan szerezni az eredetit, visszatesszük.
