### ISSUE TITLE
Server error nem található oldal hiba helyett

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#86]
Ezekre az oldalakra valamiért Server error-t ír. Nem pedig azt, hogy nem találhatóak.
![jegyzet 2019-02-24 132020](https://user-images.githubusercontent.com/8324198/53299147-151ba200-3837-11e9-961d-b7437c4e995c.jpg)
![jegyzet 2019-02-24 132138](https://user-images.githubusercontent.com/8324198/53299153-219ffa80-3837-11e9-8bb3-1003dab78996.jpg)

**Comment by andris155** [comment]
![jegyzet 2019-02-24 132238](https://user-images.githubusercontent.com/8324198/53299162-45fbd700-3837-11e9-8fc6-05bd38ed14ab.jpg)

**Comment by vngplanet** [comment]
Szia, ezeket a linkeket a google fogalmam nincs honnan vette. Pontosabban tudom honnan, a clans.hu-ról, de hogy itt miért van nem tudom

**Comment by vngplanet** [comment]
A google fogalmam nincs honnan vette ezeket a linkeket. Pontosabban tudom hogy a clans.hu-n ezek valós címek, de hogy itt miért van nem tudom.
