### ISSUE TITLE
Paypal fizetés hiba

### ISSUE THREAD

**Issue by Trywillon** [vngplanet/MineMarket#93]
A vevőktől levonja az összeget, viszont a minemarket Nem fizetett státuszba rakja őt, és nem kapja meg a vásárolt terméket

Örülnék, ha ki lenne javítva :D

**Comment by andris155** [comment]
https://github.com/vngplanet/MineMarket/issues/89

**Comment by andris155** [comment]
Szerintem soha. A clans.hu-nak kellene megoldania, de nem igazán foglalkoznak a MineMarket-tel.

**Comment by andris155** [comment]
Sokkal jobb a Buycraft, de sokkal drágább is. :/
