### ISSUE TITLE
API URL ERROR 401 - Unauthorized!

### ISSUE THREAD

**Issue by B1gLev** [vngplanet/MineMarket#98]
Ez a hiba csak nálam merült fel eddig? Vagy aki használta már a mm apit annak működött-e?
![image](https://user-images.githubusercontent.com/40140251/71444507-185f1300-2712-11ea-9409-3ea9c692fc80.png)
Örülnék ha működőképes lenne az API

**Comment by andris155** [comment]
Ubuntu-n elég rosszul fut a Minecraft. Ha Minecraft szervert futtatsz szerintem nem szerencsés.
Egyébként meg kell adni gondolom mit szeretnél és úgy működnie kell.

**Comment by B1gLev** [comment]
Értem, lényegében gondolom így kéne működnie az api-nak, hogy
http://minemarket.hu/api/?format=json&apikey=ZFveeQbcaSOuXOvaVopd&method=getUserCredit&user={játékos
neve}
Csak ugye itt magát az oldalt nem igazán érem el amivel elvileg
komunikálnia kéne az API-nak.
Ugyan akkor megnéztem egy másik api-t aminek a mechanikája szerintem egyező
az is json alapú. (Nyilván a két dolog nem függ össze)
Itt már teszteltem is és vissza kaptam a json data értékeit.
http://mcapi.us/server/status?ip=173.212.238.182&port=25565

Mellesleg Ubuntun mivel rosszabb egy Minecraft szerver üzemeltetése?


András Marczinkó <notifications@github.com> ezt írta (időpont: 2019. dec.
25., Sze, 14:37):

**Comment by vngplanet** [comment]
Az api működőképes. Olvass dokumentációt, és a 401-es státuszkódról is.
