### ISSUE TITLE
MMAPI hiba

### ISSUE THREAD

**Issue by SuliPort** [vngplanet/MineMarket#99]
Letöltöttem egy plugint (mert hülye vagyok az APIhoz :D) amivel jóváírhatok, utalhatok, levonhatok... kreditet játékon belül. De sosem érkezik válasz a kiszolgálótól, pedig megadtam a kulcsokat. Mit tehetek?
https://www.spigotmc.org/resources/mmcredits-minemarket-credits-hu.22805/ a plugin

**Comment by B1gLev** [comment]
> Letöltöttem egy plugint (mert hülye vagyok az APIhoz :D) amivel jóváírhatok, utalhatok, levonhatok... kreditet játékon belül. De sosem érkezik válasz a kiszolgálótól, pedig megadtam a kulcsokat. Mit tehetek?
> https://www.spigotmc.org/resources/mmcredits-minemarket-credits-hu.22805/ a plugin

Esetleg nézd meg a szervernek a log mappáját, hátha ír valami hibát mikor próbál csatlakozni a kiszolgálóhoz. Másrészt biztos jók a kulcsok?

**Comment by SuliPort** [comment]
Tudunk esetleg chatelni? Jelentősen könnyebb lenne. A kulcsokat ellenőriztem, jók. Újrageneráljam őket? A log nem jelez hibát.

**Comment by B1gLev** [comment]
> Tudunk esetleg chatelni? Jelentősen könnyebb lenne. A kulcsokat ellenőriztem, jók. Újrageneráljam őket? A log nem jelez hibát.

Persze, Discord nevem BigLev#2342

**Comment by SuliPort** [comment]
Megjelöltelek, köszi :)
